name: Cold World
favicon: null
layout_spectrum: 0.13889496680349112
typography_spectrum: 0.11267300136387348
title: 'A blog about Sneakers, Life, and everything in it.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8740588512737304
  lightness: 0.6193326162174344
  saturation: 0.1462337695993483
  rhythmicContrast: 0.14166973205283284
purpose: []
