name: Cold World
favicon: null
layout_spectrum: 0.8125
typography_spectrum: 0.807565
title: 'A blog about Sneakers, Life, and everything in it.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C8C8'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.874058
  lightness: 0.619332
  saturation: 0.146233
  rhythmicContrast: 0.155427
purpose: []
