name: Cold World
favicon: null
layout_spectrum: 0.77845
typography_spectrum: 0.60889
title: 'A blog about Sneakers, Life, and everything in it.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74755174-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#817a74'
    - '#574634'
    - '#c8c8be'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
