analytics: {}
color:
  brandColors:
    - '#C8C8C8'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.874058
  lightness: 0.619332
  rhythmicContrast: 0.155427
  saturation: 0.146233
cta: {}
layout_spectrum: 0.8125
name: Cold World
opengraph: {}
purpose: []
typography_spectrum: 0.807565
