name: Cold World
favicon: null
layout_spectrum: 0.32692
typography_spectrum: 0.60889
title: 'A blog about Sneakers, Life, and everything in it.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74755174-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020200'
    - '#930303'
    - '#dd9302'
    - '#695607'
    - '#7cb885'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
